name: CI/CD Cloud Run

on:
  push:
    branches: [ "main" ]  # merges to main will deploy

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  REPO: app-repo
  SERVICE: activedispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Artifact Registry auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build (linux/amd64) and push
        id: build
        shell: bash
        run: |
          IMAGE_BASE=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE }}
          TAG=$(git rev-parse --short=12 HEAD)
          IMAGE="$IMAGE_BASE:$TAG"
          LATEST="$IMAGE_BASE:latest"

          # buildx ensures amd64 (Cloud Run requirement)
          docker buildx create --use 2>/dev/null || true
          docker buildx build --platform linux/amd64 -t "$IMAGE" --push .

          # update :latest too (optional)
          docker buildx imagetools create -t "$LATEST" "$IMAGE"

          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"

      - name: Pin image in service.yaml
        run: |
          IMAGE="${{ steps.build.outputs.image }}"
          sed -i 's#image: .*#image: '"$IMAGE"'#' cloudrun/service.yaml
          echo "Pinned image to $IMAGE"

      - name: Deploy to Cloud Run (replace service)
        run: |
          gcloud run services replace cloudrun/service.yaml \
            --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }}
