name: CI + Deploy to Cloud Run

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  REPO: app-repo
  SERVICE: activedispatch

concurrency:
  group: cicd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm test
        env:
          NODE_ENV: test
          LOG_LEVEL: warn

  build-and-deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      # Auth to Google (sets ADC)
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Install gcloud for the deploy step
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # Configure Docker to use gcloud's cred helper
      - name: Configure Artifact Registry helper
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build (linux/amd64) and push
        id: build
        shell: bash
        run: |
          set -euo pipefail
          IMAGE_BASE=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE }}
          TAG=$(git rev-parse --short=12 HEAD)
          IMAGE="$IMAGE_BASE:$TAG"
          LATEST="$IMAGE_BASE:latest"

          docker buildx create --use 2>/dev/null || true
          docker buildx build --platform linux/amd64 -t "$IMAGE" --push .

          docker buildx imagetools create -t "$LATEST" "$IMAGE"

          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"

      - name: Pin image in service.yaml
        run: |
          IMAGE="${{ steps.build.outputs.image }}"
          sed -i 's#image: .*#image: '"$IMAGE"'#' cloudrun/service.yaml
          echo "Pinned image to $IMAGE"

      - name: Deploy to Cloud Run (replace service)
        run: |
          gcloud run services replace cloudrun/service.yaml \
            --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }}
